version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: app/dockerfile
    container_name: chat-pdf-backend
    ports:
      - "8000:80"
    networks:
      - chat-pdf-network

  frontend:
    build:
      context: .
      dockerfile: ui/dockerfile
    container_name: chat-pdf-frontend
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://backend:80
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    depends_on:
      - backend
    networks:
      - chat-pdf-network

networks:
  chat-pdf-network:
    driver: bridge