version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: app/dockerfile
    container_name: chat-pdf-backend
    ports:
      - "8000:8000"
      - "5678:5678"
    networks:
      - chat-pdf-network
    working_dir: /code
    volumes:
      - ./app:/code/app
      - ./pyproject.toml:/code/pyproject.toml
      - ./uv.lock:/code/uv.lock
    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload",
      ]

  frontend:
    build:
      context: .
      dockerfile: ui/dockerfile
    container_name: chat-pdf-frontend
    ports:
      - "8501:8501"
    volumes:
      - ./ui:/code/ui
    environment:
      - API_BASE_URL=http://backend:8000
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    depends_on:
      - backend
    networks:
      - chat-pdf-network

networks:
  chat-pdf-network:
    driver: bridge