FROM python:3.11-slim

WORKDIR /code

# Copia os arquivos de configuração necessários
COPY ../pyproject.toml .
COPY ../uv.lock .

# Install uv
RUN pip install uv

RUN uv sync --frozen --no-install-project --no-dev --no-cache --only-group ui

# Copy UI code
COPY ./ui /code/ui

# Expose Streamlit port
EXPOSE 8501

# Configure Streamlit
ENV STREAMLIT_SERVER_PORT=8501
ENV STREAMLIT_SERVER_ADDRESS=0.0.0.0
ENV STREAMLIT_SERVER_HEADLESS=true
ENV STREAMLIT_BROWSER_GATHER_USAGE_STATS=false

# Start Streamlit
CMD ["streamlit", "run", "ui/chat.py"]